# Base Configuration for Singer Classification Project
# This file contains common settings shared across all experiments

# Project settings
project:
  name: "singer_classification"
  version: "1.0"
  author: "DeepMIR Student"
  seed: 42

# Dataset configuration
dataset:
  name: "artist20"
  root_path: "data/processed"
  train_json: "data/processed/train.json"
  val_json: "data/processed/val.json"
  test_dir: "data/processed/test"
  num_classes: 20
  sample_rate: 16000
  channels: 1  # mono

# Audio preprocessing
audio:
  sample_rate: 16000
  n_fft: 4096  # Reduced from 2048 to handle shorter audio chunks
  hop_length: 512  # Reduced proportionally
  n_mels: 128
  f_min: 80.0
  f_max: 8000.0
  max_duration: 5.0  # seconds
  normalize: true

# Data splitting
data_split:
  train_ratio: 0.8
  val_ratio: 0.2
  test_ratio: 0.0  # test set is predefined
  stratify: true

# Training settings
training:
  batch_size: 16
  num_epochs: 60
  learning_rate: 0.001
  weight_decay: 0.0001
  early_stopping_patience: 10
  save_best_only: true

# Evaluation settings
evaluation:
  metrics: ["top1_accuracy", "top3_accuracy", "confusion_matrix"]
  save_predictions: true
  save_probabilities: false

# Logging and experiment tracking
logging:
  level: "INFO"
  save_logs: true
  log_dir: "results/logs"
  experiment_name: null  # will be set automatically

# WandB settings
wandb:
  project: "singer_classification"
  entity: null  # set your wandb username here
  log_model: false
  log_gradients: false
  log_freq: 10

# Device settings
device:
  use_cuda: "auto"  # auto-detect GPU availability
  device_id: 0
  num_workers: 2    # Reduced for Colab compatibility
  pin_memory: true
  force_cpu: false  # Set to true for local development without GPU

# Output paths
paths:
  checkpoints: "results/checkpoints"
  predictions: "results/predictions"
  visualizations: "results/visualizations"
  processed_data: "data/processed"
  features: "data/processed/features"

# Reproducibility
reproducibility:
  deterministic: true
  benchmark: false
  set_seed_everywhere: true